version: '3.2'

services:
  php:
    image: yiisoftware/yii2-php:7.2-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - .:/app:delegated
    ports:
      - 10080:80
    links:
      - mariadb
    # environment:
    #   - COMPOSE_CONVERT_WINDOWS_PATHS=1

  mariadb:
    image: mariadb:10.3
    volumes:
      # - ./docker/dbdata:/var/lib/mysql
      - apps_persistent:/var/lib/mysql
    ports:
      - 13306:3306
      # - 3306
    restart: always
    environment:
      - TZ=Asia/Jakarta
      # - MYSQL_USER=apps_data
      # - MYSQL_PASSWORD=pass_apps_data
      - MYSQL_ROOT_PASSWORD=admin_db
      - MYSQL_DATABASE=apps_docker

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mariadb
    ports:
      - 18181:80
    environment:
      - PMA_HOST=mariadb
      
volumes:
  apps_persistent:
